api = "0.2"

[buildpack]
id = "google.java.appengine"
version = "0.0.1"
name = "Google - Java - App Engine"

[[stacks]]
id = "google.java11"

# TODO: Remove these when the next nightly candidates build.
[[stacks]]
id = "com.google.cloud.appengine.base"

[[stacks]]
id = "com.google.cloud.appengine.java11"
