api = "0.2"

[buildpack]
id = "google.python.webserver"
version = "0.0.1"
name = "Google - Python - webserver"

[[stacks]]
id = "google.python37"

[[stacks]]
id = "google.python38"

# TODO: Remove these when the next nightly candidates build.
[[stacks]]
id = "com.google.cloud.appengine.base"

[[stacks]]
id = "com.google.cloud.appengine.python37"

[[stacks]]
id = "com.google.cloud.appengine.python38"
