api = "0.2"

[buildpack]
id = "google.dotnet.publish"
version = "0.0.1"
name = "Google - .NET - Publish"

[[stacks]]
id = "google"

[[stacks]]
id = "google.base"

# TODO: Remove these when the next nightly candidates build.
[[stacks]]
id = "com.google.cloud.appengine.base"

[[stacks]]
id = "com.google.cloud.appengine.dotnet3"
