api = "0.2"

[buildpack]
id = "google.python.runtime"
version = "0.0.1"
name = "Google - Python - Runtime"

[[stacks]]
id = "google"

[[stacks]]
id = "com.google.cloud"

[[stacks]]
id = "com.google.cloud.appengine.base"
