description = "Builder for the GCF Python 3.8 runtime"

[[buildpacks]]
  id = "google.python.pip"
  uri = "pip.tgz"

[[buildpacks]]
  id = "google.python.functions-framework"
  uri = "functions_framework.tgz"

[[order]]
  [[order.group]]
    id = "google.python.pip"
    optional = true

  [[order.group]]
    id = "google.python.functions-framework"

[stack]
  id = "com.google.cloud.appengine.python38"
  build-image = "gcr.io/gae-runtimes/buildpacks/python38/build"
  run-image = "gcr.io/gae-runtimes/buildpacks/python38/run"

[lifecycle]
  version = "0.6.1"
