api = "0.2"

[buildpack]
id = "google.dotnet.appengine"
version = "0.9.0"
name = "Google - .NET - App Engine"

[[stacks]]
id = "google.base"

[[stacks]]
id = "google.dotnet3"

# TODO: Remove these when the next nightly candidates build.
[[stacks]]
id = "com.google.cloud.appengine.base"

[[stacks]]
id = "com.google.cloud.appengine.dotnet3"
