api = "0.2"

[buildpack]
id = "google.dotnet.runtime"
version = "0.9.0"
name = "Google - .NET - Runtime"

[[stacks]]
id = "google"

# TODO: Remove these when the next nightly candidates build.
[[stacks]]
id = "com.google.cloud.appengine.base"
