api = "0.2"

[buildpack]
id = "google.php.appengine"
version = "0.0.1"
name = "Google - PHP - App Engine"

[[stacks]]
id = "com.google.cloud"

[[stacks]]
id = "com.google.cloud.appengine.base"

[[stacks]]
id = "com.google.cloud.appengine.php73"

[[stacks]]
id = "com.google.cloud.appengine.php74"
