api = "0.2"

[buildpack]
id = "google.nodejs.npm"
version = "0.0.1"
name = "Google - Node.js - NPM"

[[stacks]]
id = "google"

[[stacks]]
id = "google.nodejs10"

[[stacks]]
id = "google.nodejs12"

# TODO: Remove these when the next nightly candidates build.
[[stacks]]
id = "com.google.cloud.appengine.base"

[[stacks]]
id = "com.google.cloud.appengine.nodejs10"

[[stacks]]
id = "com.google.cloud.appengine.nodejs12"