api = "0.2"

[buildpack]
id = "google.ruby.appengine_validation"
version = "0.0.1"
name = "Google - Ruby - App Engine Validation"

[[stacks]]
id = "com.google.cloud"

[[stacks]]
id = "google.ruby25"

# TODO: Remove these when the next nightly candidates build.
[[stacks]]
id = "com.google.cloud.appengine.base"

[[stacks]]
id = "com.google.cloud.appengine.ruby25"
