api = "0.2"

[buildpack]
id = "google.nodejs.firebase-functions"
version = "0.9.0"
name = "Google - Node.js - Firebase SDK for Cloud Functions"

[[stacks]]
id = "google"

[[stacks]]
id = "google.nodejs10"

[[stacks]]
id = "google.nodejs12"
