api = "0.2"

[buildpack]
id = "google.go.runtime"
version = "0.0.1"
name = "Google - Go - Runtime"

[[stacks]]
id = "google"

# TODO: Remove these when the next nightly candidates build.
[[stacks]]
id = "com.google.cloud.appengine.base"
