api = "0.2"

[buildpack]
id = "google.php.composer-gcp-build"
version = "0.9.0"
name = "Google - PHP - Composer gcp-build"

[[stacks]]
id = "google.php73"

[[stacks]]
id = "google.php74"

[[stacks]]
id = "com.google.cloud.appengine.base"

[[stacks]]
id = "com.google.cloud.appengine.php73"

[[stacks]]
id = "com.google.cloud.appengine.php74"
